//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class URLMapper
    {
        public int Id { get; set; }

       
        public string shortURL { get; set; }
        [Required(ErrorMessage = "Please enter  url ")]
        [RegularExpression(@"^https?://([a-z0-9-]+\.)*mydeal\.com\.au(/.*)?$", ErrorMessage = "Please enter  url in the correct format ")]
        public string longUrl { get; set; }

    }
}
